services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    networks:
      - traefik-public
      - default
      - observability

  loki:
    image: grafana/loki:latest
    restart: always
    volumes:
      - loki-data:/loki
    networks:
      - traefik-public
      - default
      - observability

  tempo:
    image: grafana/tempo:latest
    restart: always
    command: ["-config.file=/etc/tempo.yml"]
    user: "0:0"  # Run as root to ensure write permissions
    volumes:
      - ./infra/tempo/tempo.yml:/etc/tempo.yml
      - tempo-data:/tmp/tempo
    networks:
      - traefik-public
      - default
      - observability

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/grafana/dashboards:/etc/grafana/dashboards
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - traefik-public
      - default
      - observability
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.${STACK_NAME?Variable not set}-grafana.loadbalancer.server.port=3000
      - traefik.http.routers.${STACK_NAME?Variable not set}-grafana-http.rule=Host(`grafana.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-grafana-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?Variable not set}-grafana-https.rule=Host(`grafana.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-grafana-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-grafana-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-grafana-https.tls.certresolver=le
      - traefik.http.routers.${STACK_NAME?Variable not set}-grafana-http.middlewares=https-redirect

volumes:
  prometheus-data:
  loki-data:
  tempo-data:
  grafana-data:

networks:
  traefik-public:
    external: true
  observability:
    name: observability